[package]
name = "errata-macros"
version = "0.1.0"
edition = "2021"

description = "The proc macro behind errata."
license = "MIT"

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.38", features = ["full"] }

[lib]
proc-macro = true

